# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Choconews
description: True choconews for once.

author:
  name: Chocorean
  email: chocorean -at- pm.me
  mailto: chocorean@pm.me
#twitter_username: jekyllrb
github_username:  chocorean

domain: chocorean.github.io
url: https://chocorean.github.io
baseurl: /blog

# Build settings
theme: minima
plugins:

collections:
  posts:
    output: true
    permalink: /articles/:title

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
